"""Linear algebra utilities: vectors, matrices, decompositions, linear systems."""

from .vector import (
    dot,
    norm,
    normalize,
    angle_between,
    cross,
    project,
    is_orthogonal_vectors,
)
from .matrix import (
    identity,
    zeros,
    ones,
    random_matrix,
    transpose,
    trace,
    rank,
    determinant,
    inverse,
    pseudo_inverse,
    is_symmetric,
    is_orthogonal_matrix,
    is_positive_definite,
    matmul,
    hadamard,
    kronecker,
)
from .decomposition import lu, qr, svd, eig, eigh, cholesky
from .solve import solve, least_squares, solve_triangular

__all__ = [
    "dot",
    "norm",
    "normalize",
    "angle_between",
    "cross",
    "project",
    "is_orthogonal_vectors",
    "identity",
    "zeros",
    "ones",
    "random_matrix",
    "transpose",
    "trace",
    "rank",
    "determinant",
    "inverse",
    "pseudo_inverse",
    "is_symmetric",
    "is_orthogonal_matrix",
    "is_positive_definite",
    "matmul",
    "hadamard",
    "kronecker",
    "lu",
    "qr",
    "svd",
    "eig",
    "eigh",
    "cholesky",
    "solve",
    "least_squares",
    "solve_triangular",
]
